Exception in thread "main" java.lang.RuntimeException: Absolutely new RuntimeException
	at OptimizationTests.UnusedLoopRemoval.Throw_01.Main.loop(Main.java:9)
	at OptimizationTests.UnusedLoopRemoval.Throw_01.Main.main(Main.java:15)
